### ISSUE TITLE
Less restrictive license

### ISSUE THREAD

**Issue by tomasz-sodzawiczny** [nossas/slate-editor#63]
The project has a lot of great solutions that can be reused in many products - would you maybe consider switching to some less restrictive license (maybe [MIT](https://opensource.org/licenses/MIT)?), so commercial, non-opensource projects can use it too? 

And if you don't want to do that for the whole project for some reason - maybe it's possible for some smaller, reusable parts? (See e.g. https://github.com/nossas/slate-editor/issues/62).

**Comment by sebastianiorga** [comment]
Not affiliated to the project but in case other people are wondering(as I was): unless you are building a commercial **closed-source** software product that you are then selling, the GPL3 does not require you to do anything, as far as I can tell.

See also discussion at https://stackoverflow.com/a/2280784/1908371 

So for instance using and modifying this software in a SaaS context doesn't require you to do anything. Particularly since your Javascript code is open-source(ish) by default anyway.

If you were packaging it inside a proprietary Javascript library that you then sold that would be different.

I am not a lawyer yada yada

**Comment by tomasz-sodzawiczny** [comment]
@sebastianiorga thanks for the input.
You're probably right - but still the licence will scare a lot of people/companies off, or require consulting the lawyers, etc. Why make it difficult?

**Comment by gabrielrtakeda** [comment]
@tomasz-sodzawiczny, @sebastianiorga, thanks for expressing your opinions and for the concern about the restrictions of the license adopted in the package today. We discussed about it and, we come to the conclusion that it makes sense switching to the MIT... I will make this change but, I believe @sebastianiorga is right... to avoid generating more doubts, I think the MIT is the solution 😛
