### ISSUE TITLE
Why use multiple packages rather than just one package with the methods inside like ReactJS or other doe ?

### ISSUE THREAD

**Issue by Hocoh** [nossas/slate-editor#72]
I have seen your page https://github.com/nossas/slate-editor/tree/develop/packages and I wonder by pure curiosity why you haven't merge all the package in the main package, I assume it's for performance but at the end of the day the gain is minimal for the boilerplate IMHO ?  So just a basic question, 

thanks for your awesome work

**Comment by gabrielrtakeda** [comment]
I have "splitted" the `slate-editor` plugins into multiple packages to permit other developers that already have its own implementation of `slate`, instead of use `slate-editor` itself, can use which plugin he desire... without having to "download" the whole `slate-editor` package in its project. The "fuse" that take me to decide to split plugins into separated packages was [this issue](https://github.com/nossas/slate-editor/issues/62).
